name: CI/CD Pipeline AWS EC2

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2

      - name: Prepare Firestore Credentials
        run: echo "${{ secrets.FIRESTORE_APPLICATION_CREDENTIALS }}" > firestore-credentials.json

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        env:
          FIRESTORE_APPLICATION_CREDENTIALS: ${{ secrets.FIRESTORE_APPLICATION_CREDENTIALS }}
        run: ./gradlew build

  # test:
  #   name: Tests
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout repository code
  #       uses: actions/checkout@v2

  #     - name: Set up JDK 17
  #       uses: actions/setup-java@v3
  #       with:
  #         distribution: "temurin"
  #         java-version: "17"

  #     - name: Set up Gradle
  #       uses: gradle/gradle-build-action@v2

  #     - name: Prepare Firestore Credentials
  #       run: echo "${{ secrets.FIRESTORE_APPLICATION_CREDENTIALS }}" > firestore-credentials.json

  #     - name: Test and analyze code
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #         FIRESTORE_APPLICATION_CREDENTIALS: ${{ secrets.FIRESTORE_APPLICATION_CREDENTIALS }}
  #       run: ./gradlew test

  deploy:
    name: Deploy to AWS EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v2

      - name: Install Java 17
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2

      - name: Prepare Firestore Credentials
        run: echo "${{ secrets.FIRESTORE_APPLICATION_CREDENTIALS }}" > firestore-credentials.json

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Write SSH key
        run: |
          echo "${{ secrets.SSH_KEY }}" > lisungui_server_key.pem
          chmod 600 lisungui_server_key.pem

      # - name: Ensure target directory exists
      #   run: ssh -o StrictHostKeyChecking=no -i lisungui_server_key.pem ${SSH_USER}@${SSH_HOST} "mkdir -p /home/ec2-user/app"
      - name: Copy files to EC2
        run: |
          chmod +x startup.sh

      - name: Create .env file on the remote server
        run: |
          ssh -o StrictHostKeyChecking=no -i lisungui_server_key.pem ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
            echo FIRESTORE_APPLICATION_CREDENTIALS=\$(echo ${{ secrets.ENCODED_FIRESTORE_CREDENTIALS }} | base64 --decode) > /home/${{ secrets.SSH_USER }}/app/.env
          "

      - name: Deploy to EC2
        env:
          FIRESTORE_APPLICATION_CREDENTIALS: ${{ secrets.FIRESTORE_APPLICATION_CREDENTIALS }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
        run: |
          ssh -o StrictHostKeyChecking=no -i lisungui_server_key.pem ${SSH_USER}@${SSH_HOST} "
            mkdir -p /home/${SSH_USER}/app &&
            cd /home/${SSH_USER}/app &&
            if [ -f gradlew ]; then
              chmod +x gradlew
              ./gradlew bootRun
            else
              echo 'gradlew not found'
            fi &&
            if [ -f /home/${SSH_USER}/app/*.jar ]; then
              java -jar /home/${SSH_USER}/app/*.jar
            else
              echo 'Jar file not found'
            fi
          "

          sleep 10  # Short pause to ensure app is up
          curl https://${{ secrets.SSH_HOST }}:8080/
